# Generated by Django 6.0.3 on 2026-03-10 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('New', 'New task'), ('In progress', 'Active task'), ('Pending', 'Pending...'), ('Blocked', 'Blocked'), ('Done', 'Finished')], default='New', max_length=20, verbose_name='Статус подзадачи'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='my_app.task', verbose_name='Основная задача'),
        ),
    ]
